name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # API Section
      - name: Install API dependencies
        run: npm install
        working-directory: API

      - name: Run Snyk on API
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
         npx snyk auth $SNYK_TOKEN
         npx snyk test --policy-file=snyk.policy
        working-directory: API

      # Frontend Section
      - name: Install Frontend dependencies
        run: npm install
        working-directory: Frontend

      - name: Run Snyk on Frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npx snyk auth $SNYK_TOKEN
          npx snyk test --policy-file=snyk.policy
        working-directory: Frontend

      # Install and Run SonarCloud on API
      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-4.8.0.2856-linux sonar-scanner
          export PATH=$PATH:$(pwd)/sonar-scanner/bin

      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=AndrewTroll_APDS7311POE \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
        working-directory: API
