name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # API Section
      - name: Install API dependencies
        run: npm install
        working-directory: API

      - name: Run Snyk on API
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
         npx snyk auth $SNYK_TOKEN
         npx snyk test --policy-file=snyk.policy
        working-directory: API

      # Frontend Section
      - name: Install Frontend dependencies
        run: npm install
        working-directory: Frontend

      - name: Run Snyk on Frontend
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npx snyk auth $SNYK_TOKEN
          npx snyk test  --policy-file=snyk.policy
        working-directory: Frontend

             # Run SonarCloud on API
      - name: SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=AndrewTroll_APDS7311POE \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
        working-directory: API
